-- QuizzFoot — 150 Additional Questions (Seed 2)
-- Run in Supabase SQL Editor AFTER seed.sql

-- ═══ LIGUE 1 (extra) ═══
INSERT INTO questions (type, question, choices, answer, explanation, difficulty, category_id, tags, competition) VALUES
('mcq','Quel joueur a marqué le plus de buts en une saison de Ligue 1 ?','["Josip Skoblar","Carlos Bianchi","Kylian Mbappé","Zlatan Ibrahimović"]','Josip Skoblar','Skoblar a inscrit 44 buts avec l''OM en 1970-1971.',5,(SELECT id FROM categories WHERE slug='ligue-1'),'{"records"}','Ligue 1'),
('mcq','Quel stade accueille les matchs du RC Lens ?','["Stade Bollaert-Delelis","Stade Vélodrome","Stade de la Meinau","Stade Geoffroy-Guichard"]','Stade Bollaert-Delelis','Bollaert-Delelis, situé à Lens, a une capacité de 38 000 places.',1,(SELECT id FROM categories WHERE slug='ligue-1'),'{"stades"}','Ligue 1'),
('tf','L''AS Saint-Étienne a remporté 10 titres de champion de France.','["Vrai","Faux"]','Vrai','Les Verts ont été champions 10 fois, un record jusqu''en 2022.',2,(SELECT id FROM categories WHERE slug='ligue-1'),'{"histoire"}','Ligue 1'),
('mcq','Quel club a remporté la Coupe de France le plus souvent ?','["Paris Saint-Germain","Olympique de Marseille","AS Saint-Étienne","AS Monaco"]','Paris Saint-Germain','Le PSG a remporté 15 Coupes de France.',2,(SELECT id FROM categories WHERE slug='ligue-1'),'{"coupes"}','Coupe de France'),
('mcq','Qui a été le premier entraîneur étranger champion de France ?','["Vahid Halilhodžić","Carlo Ancelotti","Unai Emery","Thomas Tuchel"]','Vahid Halilhodžić','Halilhodžić a mené Lille au titre en 2011.',4,(SELECT id FROM categories WHERE slug='ligue-1'),'{"entraîneurs"}','Ligue 1'),
('whoami','J''ai été formé à Lyon, j''ai joué à Madrid et j''ai marqué le but décisif en finale de Coupe du Monde 2006.','["Zinedine Zidane","Karim Benzema","Florent Malouda","Juninho"]','Karim Benzema','Benzema, Ballon d''Or 2022, a été formé à l''OL.',3,(SELECT id FROM categories WHERE slug='ligue-1'),'{"légendes"}','Ligue 1'),
('mcq','Combien de clubs la Ligue 1 compte-t-elle depuis 2023 ?','["18","20","22","16"]','18','La Ligue 1 est passée de 20 à 18 clubs à partir de la saison 2023-2024.',2,(SELECT id FROM categories WHERE slug='ligue-1'),'{"actualité"}','Ligue 1'),
('mcq','Quel joueur a reçu le plus de cartons rouges en Ligue 1 ?','["Cyril Rool","Franck Ribéry","Fabrice Fiorèse","Aloísio"]','Cyril Rool','Cyril Rool détient le record avec 27 rouges.',5,(SELECT id FROM categories WHERE slug='ligue-1'),'{"records"}','Ligue 1');

-- ═══ PREMIER LEAGUE (extra) ═══
INSERT INTO questions (type, question, choices, answer, explanation, difficulty, category_id, tags, competition) VALUES
('mcq','Quel gardien a le plus de clean sheets en Premier League ?','["David James","Petr Čech","Edwin van der Sar","Peter Schmeichel"]','Petr Čech','Čech détient le record avec 202 clean sheets en PL.',3,(SELECT id FROM categories WHERE slug='premier-league'),'{"records"}','Premier League'),
('mcq','Quel joueur a reçu le plus de cartons jaunes en PL ?','["Lee Bowyer","Mark Noble","Gareth Barry","Wayne Rooney"]','Gareth Barry','Gareth Barry a accumulé 123 cartons jaunes.',4,(SELECT id FROM categories WHERE slug='premier-league'),'{"records"}','Premier League'),
('tf','Tottenham a gagné la Premier League au moins une fois depuis 1992.','["Vrai","Faux"]','Faux','Tottenham n''a jamais remporté la PL. Son dernier titre de champion date de 1961.',2,(SELECT id FROM categories WHERE slug='premier-league'),'{"histoire"}','Premier League'),
('mcq','Quel est le plus grand nombre de buts marqués en un match de PL par un joueur ?','["4","5","6","7"]','5','Plusieurs joueurs ont marqué 5 buts: Shearer, Cole, Defoe, Berbatov, Agüero...',4,(SELECT id FROM categories WHERE slug='premier-league'),'{"records"}','Premier League'),
('mcq','Quel club a dépensé le plus en transferts depuis 2010 ?','["Manchester City","Chelsea","Manchester United","Liverpool"]','Manchester City','City a dépensé plus de 2 milliards d''euros en transferts depuis 2010.',2,(SELECT id FROM categories WHERE slug='premier-league'),'{"transferts"}','Premier League'),
('whoami','J''ai joué à Arsenal et suis devenu le meilleur buteur étranger de PL. Je suis français.','["Nicolas Anelka","Patrick Vieira","Thierry Henry","Robert Pirès"]','Thierry Henry','Henry a marqué 175 buts en PL avec Arsenal.',1,(SELECT id FROM categories WHERE slug='premier-league'),'{"légendes"}','Premier League'),
('mcq','Quel club a remporté la première édition de la Premier League en 1992-93 ?','["Arsenal","Blackburn Rovers","Manchester United","Leeds United"]','Manchester United','Man Utd a remporté le premier titre de PL sous Sir Alex Ferguson.',2,(SELECT id FROM categories WHERE slug='premier-league'),'{"histoire"}','Premier League'),
('mcq','Combien de buts Erling Haaland a-t-il marqués lors de sa première saison PL ?','["28","32","36","42"]','36','Haaland a battu le record avec 36 buts en une saison de PL 2022-2023.',2,(SELECT id FROM categories WHERE slug='premier-league'),'{"records"}','Premier League');

-- ═══ CHAMPIONS LEAGUE (extra) ═══
INSERT INTO questions (type, question, choices, answer, explanation, difficulty, category_id, tags, competition) VALUES
('mcq','Quel joueur a marqué le plus de buts en une seule édition de Ligue des Champions ?','["Lionel Messi","Robert Lewandowski","Cristiano Ronaldo","Neymar"]','Cristiano Ronaldo','CR7 a marqué 17 buts en 2013-2014 avec le Real Madrid.',3,(SELECT id FROM categories WHERE slug='champions-league'),'{"records"}','Champions League'),
('mcq','Quelle finale de Champions League a vu le plus de buts ?','["Real Madrid-Eintracht 1960","Liverpool-AC Milan 2005","Man United-Bayern 1999","Barcelona-Man United 2011"]','Real Madrid-Eintracht 1960','Real Madrid a battu Eintracht Francfort 7-3 en finale 1960.',5,(SELECT id FROM categories WHERE slug='champions-league'),'{"histoire"}','Champions League'),
('tf','Le FC Porto a remporté la Ligue des Champions sous José Mourinho.','["Vrai","Faux"]','Vrai','Porto a remporté la C1 en 2004 sous Mourinho, battant Monaco en finale.',2,(SELECT id FROM categories WHERE slug='champions-league'),'{"histoire"}','Champions League'),
('mcq','Quel club a remporté 3 Champions League consécutives entre 2016 et 2018 ?','["Real Madrid","FC Barcelona","Bayern Munich","AC Milan"]','Real Madrid','Le Real a gagné la C1 en 2016, 2017 et 2018 sous Zidane.',1,(SELECT id FROM categories WHERE slug='champions-league'),'{"histoire"}','Champions League'),
('whoami','J''ai marqué un doublé en finale 2014 et un but en finale 2018 de C1. Je suis gallois.','["Aaron Ramsey","Gareth Bale","Ryan Giggs","Craig Bellamy"]','Gareth Bale','Bale a marqué un doublé mémorable en finale 2018 avec le Real Madrid.',3,(SELECT id FROM categories WHERE slug='champions-league'),'{"joueurs"}','Champions League'),
('mcq','Quel club a perdu le plus de finales de Champions League ?','["Juventus","Bayern Munich","Benfica","Atletico Madrid"]','Juventus','La Juventus a perdu 7 finales de C1/Champions League.',4,(SELECT id FROM categories WHERE slug='champions-league'),'{"records"}','Champions League'),
('mcq','En quelle année la Coupe des Champions est-elle devenue la Champions League ?','["1990","1992","1995","1997"]','1992','Le format Champions League a été introduit en 1992-1993.',3,(SELECT id FROM categories WHERE slug='champions-league'),'{"histoire"}','Champions League'),
('mcq','Qui a été le premier remplaçant à marquer un hat-trick en Champions League ?','["Ole Gunnar Solskjær","Fernando Torres","Mario Gómez","Divock Origi"]','Ole Gunnar Solskjær','Solskjær a réalisé cet exploit avec Man Utd contre Juventus en 1999.',5,(SELECT id FROM categories WHERE slug='champions-league'),'{"records"}','Champions League');

-- ═══ COUPE DU MONDE (extra) ═══
INSERT INTO questions (type, question, choices, answer, explanation, difficulty, category_id, tags, competition) VALUES
('mcq','Quel pays a gagné le plus de Coupes du Monde ?','["Allemagne","Italie","Argentine","Brésil"]','Brésil','Le Brésil a remporté 5 Coupes du Monde (1958, 1962, 1970, 1994, 2002).',1,(SELECT id FROM categories WHERE slug='coupe-du-monde'),'{"histoire"}','Coupe du Monde'),
('mcq','Quel joueur a marqué le plus de buts en Coupe du Monde ?','["Ronaldo","Pelé","Miroslav Klose","Gerd Müller"]','Miroslav Klose','Klose a marqué 16 buts en 4 éditions de la Coupe du Monde.',3,(SELECT id FROM categories WHERE slug='coupe-du-monde'),'{"records"}','Coupe du Monde'),
('tf','La France a gagné 3 Coupes du Monde.','["Vrai","Faux"]','Faux','La France a gagné 2 Coupes du Monde: 1998 et 2018.',1,(SELECT id FROM categories WHERE slug='coupe-du-monde'),'{"histoire"}','Coupe du Monde'),
('mcq','Dans quel pays s''est déroulée la première Coupe du Monde en 1930 ?','["Brésil","Italie","Uruguay","Argentine"]','Uruguay','La première Coupe du Monde s''est tenue en Uruguay, qui l''a remportée.',2,(SELECT id FROM categories WHERE slug='coupe-du-monde'),'{"histoire"}','Coupe du Monde'),
('whoami','J''ai marqué un triplé en finale de Coupe du Monde 2022 mais mon équipe a perdu.','["Lionel Messi","Antoine Griezmann","Kylian Mbappé","Olivier Giroud"]','Kylian Mbappé','Mbappé a marqué un triplé en finale 2022, mais la France a perdu aux tirs au but.',1,(SELECT id FROM categories WHERE slug='coupe-du-monde'),'{"joueurs"}','Coupe du Monde'),
('mcq','Quelle est la plus large victoire en Coupe du Monde ?','["Allemagne 7-1 Brésil","Hongrie 10-1 El Salvador","Australie 31-0 Samoa","Yougoslavie 9-0 Zaïre"]','Hongrie 10-1 El Salvador','La Hongrie a battu El Salvador 10-1 en 1982.',4,(SELECT id FROM categories WHERE slug='coupe-du-monde'),'{"records"}','Coupe du Monde'),
('mcq','Quel gardien a arrêté le plus de penalties en Coupe du Monde ?','["Harald Schumacher","Gianluigi Buffon","Emiliano Martínez","Tim Krul"]','Emiliano Martínez','Martínez a été décisif en 2022 avec l''Argentine.',3,(SELECT id FROM categories WHERE slug='coupe-du-monde'),'{"joueurs"}','Coupe du Monde'),
('tf','Le Maroc est la première équipe africaine demi-finaliste de Coupe du Monde.','["Vrai","Faux"]','Vrai','Le Maroc a atteint les demi-finales au Qatar en 2022.',1,(SELECT id FROM categories WHERE slug='coupe-du-monde'),'{"histoire"}','Coupe du Monde');

-- ═══ LÉGENDES (extra) ═══
INSERT INTO questions (type, question, choices, answer, explanation, difficulty, category_id, tags, competition) VALUES
('mcq','Combien de Ballons d''Or Lionel Messi a-t-il remportés ?','["6","7","8","9"]','8','Messi a remporté 8 Ballons d''Or (2009-2012, 2015, 2019, 2021, 2023).',1,(SELECT id FROM categories WHERE slug='legendes'),'{"récompenses"}',''),
('mcq','Quel joueur est surnommé "O Fenômeno" ?','["Ronaldinho","Pelé","Ronaldo Nazário","Rivaldo"]','Ronaldo Nazário','Ronaldo Nazário, 2 fois Ballon d''Or, est surnommé O Fenômeno.',2,(SELECT id FROM categories WHERE slug='legendes'),'{"surnoms"}',''),
('tf','Diego Maradona a joué au FC Barcelone.','["Vrai","Faux"]','Vrai','Maradona a joué au Barça de 1982 à 1984 avant de rejoindre Naples.',3,(SELECT id FROM categories WHERE slug='legendes'),'{"histoire"}',''),
('whoami','J''ai marqué 77 buts en sélection brésilienne et remporté 2 Coupes du Monde.','["Ronaldo Nazário","Pelé","Romário","Neymar"]','Ronaldo Nazário','Ronaldo a marqué 62 buts en sélection (record battu depuis par Neymar).',3,(SELECT id FROM categories WHERE slug='legendes'),'{"joueurs"}',''),
('mcq','Quel joueur a le plus de sélections internationales ?','["Cristiano Ronaldo","Sergio Ramos","Bader Al-Mutawa","Gianluigi Buffon"]','Cristiano Ronaldo','CR7 a dépassé 200 sélections avec le Portugal.',2,(SELECT id FROM categories WHERE slug='legendes'),'{"records"}',''),
('mcq','Qui a été le plus jeune Ballon d''Or ?','["Lionel Messi","Ronaldo Nazário","Michael Owen","Lamine Yamal"]','Ronaldo Nazário','Ronaldo Nazário a remporté le Ballon d''Or en 1997 à 21 ans.',4,(SELECT id FROM categories WHERE slug='legendes'),'{"récompenses"}',''),
('mcq','Quel défenseur a remporté le Ballon d''Or en 2006 ?','["Paolo Maldini","Fabio Cannavaro","Alessandro Nesta","Sergio Ramos"]','Fabio Cannavaro','Cannavaro l''a remporté après avoir mené l''Italie au titre mondial.',3,(SELECT id FROM categories WHERE slug='legendes'),'{"récompenses"}',''),
('tf','Zinedine Zidane a marqué 2 buts en finale de Coupe du Monde 1998.','["Vrai","Faux"]','Vrai','Zidane a inscrit un doublé de la tête contre le Brésil (3-0).',1,(SELECT id FROM categories WHERE slug='legendes'),'{"histoire"}','');

-- ═══ TRANSFERTS (extra) ═══
INSERT INTO questions (type, question, choices, answer, explanation, difficulty, category_id, tags, competition) VALUES
('mcq','Quel est le transfert le plus cher de l''histoire ?','["Kylian Mbappé","Neymar","Philippe Coutinho","Jack Grealish"]','Neymar','Le transfert de Neymar du Barça au PSG en 2017 a coûté 222M€.',1,(SELECT id FROM categories WHERE slug='transferts'),'{"records"}',''),
('mcq','Quel joueur a été transféré pour 100M€ au Real Madrid en 2009 ?','["Kaká","Cristiano Ronaldo","Zinedine Zidane","Gareth Bale"]','Cristiano Ronaldo','CR7 a été transféré de Man Utd au Real Madrid pour 94M€ (record à l''époque).',2,(SELECT id FROM categories WHERE slug='transferts'),'{"histoire"}',''),
('tf','Antoine Griezmann a coûté plus de 100M€ au FC Barcelone.','["Vrai","Faux"]','Vrai','Griezmann a été transféré de l''Atletico au Barça pour 120M€ en 2019.',2,(SELECT id FROM categories WHERE slug='transferts'),'{"transferts"}',''),
('mcq','Quel joueur libre a signé le plus gros contrat de l''histoire ?','["Lionel Messi","Kylian Mbappé","David Alaba","Robert Lewandowski"]','Kylian Mbappé','Le contrat de Mbappé au Real Madrid en 2024 est le plus lucratif pour un agent libre.',3,(SELECT id FROM categories WHERE slug='transferts'),'{"actualité"}',''),
('mcq','Quel club a vendu Erling Haaland à Manchester City ?','["Red Bull Salzbourg","Bayern Munich","Borussia Dortmund","Molde FK"]','Borussia Dortmund','Haaland a quitté Dortmund pour City en 2022 pour sa clause de 60M€.',2,(SELECT id FROM categories WHERE slug='transferts'),'{"transferts"}',''),
('mcq','Pour combien Zinedine Zidane a-t-il été transféré au Real Madrid en 2001 ?','["50M€","66M€","75M€","80M€"]','75M€','Zidane a été transféré de la Juventus au Real Madrid pour 75M€.',3,(SELECT id FROM categories WHERE slug='transferts'),'{"histoire"}',''),
('whoami','J''ai coûté 135M€ en 2017, établissant le 2e transfert le plus cher. Je suis français.','["Paul Pogba","Antoine Griezmann","Kylian Mbappé","Ousmane Dembélé"]','Kylian Mbappé','Mbappé a été transféré de Monaco au PSG pour 180M€ au total.',2,(SELECT id FROM categories WHERE slug='transferts'),'{"transferts"}',''),
('tf','Le marché des transferts d''été se termine le 31 août en Europe.','["Vrai","Faux"]','Vrai','La deadline du mercato estival est fixée au 31 août dans les ligues européennes.',1,(SELECT id FROM categories WHERE slug='transferts'),'{"règles"}','');

-- ═══ TACTIQUE (extra) ═══
INSERT INTO questions (type, question, choices, answer, explanation, difficulty, category_id, tags, competition) VALUES
('mcq','Quelle formation est connue sous le nom de "catenaccio" ?','["4-4-2","3-5-2","5-3-2","4-3-3"]','5-3-2','Le catenaccio italien utilise une défense à 5 avec un libéro.',3,(SELECT id FROM categories WHERE slug='tactique'),'{"formations"}',''),
('mcq','Quel entraîneur est considéré comme le père du tiki-taka ?','["Johan Cruyff","Pep Guardiola","Luis Aragonés","Vicente del Bosque"]','Johan Cruyff','Cruyff a posé les bases du jeu de position au Barça dans les années 90.',3,(SELECT id FROM categories WHERE slug='tactique'),'{"entraîneurs"}',''),
('tf','Le "gegenpressing" est un style défensif passif.','["Vrai","Faux"]','Faux','Le gegenpressing est un pressing immédiat après la perte du ballon, popularisé par Klopp.',2,(SELECT id FROM categories WHERE slug='tactique'),'{"tactiques"}',''),
('mcq','Combien de joueurs maximum sur le terrain par équipe ?','["10","11","12","13"]','11','Chaque équipe aligne 11 joueurs maximum, dont un gardien.',1,(SELECT id FROM categories WHERE slug='tactique'),'{"règles"}',''),
('mcq','Qu''est-ce qu''un "faux 9" ?','["Un gardien qui monte","Un attaquant qui décroche","Un latéral offensif","Un milieu box-to-box"]','Un attaquant qui décroche','Le faux 9 décroche au milieu pour créer des espaces, comme Messi au Barça.',3,(SELECT id FROM categories WHERE slug='tactique'),'{"tactiques"}',''),
('mcq','Quel système de jeu utilise traditionnellement le FC Barcelone ?','["4-4-2","4-3-3","3-4-3","4-2-3-1"]','4-3-3','Le 4-3-3 est la formation historique du Barça depuis l''ère Cruyff.',2,(SELECT id FROM categories WHERE slug='tactique'),'{"formations"}',''),
('whoami','J''ai inventé le "football total" avec les Pays-Bas en 1974.','["Johan Cruyff","Rinus Michels","Louis van Gaal","Marco van Basten"]','Rinus Michels','Rinus Michels est le père du "football total" avec l''Ajax et les Pays-Bas.',4,(SELECT id FROM categories WHERE slug='tactique'),'{"entraîneurs"}',''),
('tf','Le VAR a été utilisé pour la première fois en Coupe du Monde en 2018.','["Vrai","Faux"]','Vrai','La VAR a été introduite lors de la Coupe du Monde 2018 en Russie.',2,(SELECT id FROM categories WHERE slug='tactique'),'{"règles"}','');

-- ═══ STADES (extra) ═══
INSERT INTO questions (type, question, choices, answer, explanation, difficulty, category_id, tags, competition) VALUES
('mcq','Quel est le plus grand stade de football au monde ?','["Camp Nou","Wembley","Stade de France","Rungrado May Day"]','Rungrado May Day','Le Rungrado May Day en Corée du Nord peut accueillir 114 000 spectateurs.',3,(SELECT id FROM categories WHERE slug='stades'),'{"records"}',''),
('mcq','Quel stade accueille la finale de Champions League en 2024 ?','["Wembley","Stade de France","Atatürk","Allianz Arena"]','Wembley','La finale 2024 s''est jouée à Wembley, Londres.',2,(SELECT id FROM categories WHERE slug='stades'),'{"champions-league"}','Champions League'),
('tf','Le Camp Nou peut accueillir plus de 90 000 spectateurs.','["Vrai","Faux"]','Vrai','Le Camp Nou a une capacité de 99 354 places (avant rénovation).',2,(SELECT id FROM categories WHERE slug='stades'),'{"stades"}',''),
('mcq','Dans quelle ville se trouve le stade Santiago Bernabéu ?','["Barcelone","Séville","Madrid","Valence"]','Madrid','Le Bernabéu est le stade du Real Madrid, situé dans le centre de Madrid.',1,(SELECT id FROM categories WHERE slug='stades'),'{"stades"}',''),
('mcq','Quel stade est surnommé "le théâtre des rêves" ?','["Anfield","Old Trafford","Emirates Stadium","Stamford Bridge"]','Old Trafford','Old Trafford, stade de Man Utd, est surnommé "Theatre of Dreams".',2,(SELECT id FROM categories WHERE slug='stades'),'{"stades"}',''),
('mcq','Quelle est la capacité du Stade de France ?','["60 000","70 000","80 000","90 000"]','80 000','Le Stade de France à Saint-Denis peut accueillir 80 698 spectateurs.',2,(SELECT id FROM categories WHERE slug='stades'),'{"stades"}',''),
('whoami','Je suis un stade mythique de Liverpool, célèbre pour mon "You''ll Never Walk Alone".','["Old Trafford","Anfield","Goodison Park","Emirates"]','Anfield','Anfield est le stade du Liverpool FC depuis 1892.',1,(SELECT id FROM categories WHERE slug='stades'),'{"stades"}',''),
('tf','Le Maracanã a accueilli deux finales de Coupe du Monde.','["Vrai","Faux"]','Vrai','Le Maracanã a accueilli les finales de 1950 et 2014.',2,(SELECT id FROM categories WHERE slug='stades'),'{"histoire"}','');

-- ═══ EQUIPE DE FRANCE (extra) ═══
INSERT INTO questions (type, question, choices, answer, explanation, difficulty, category_id, tags, competition) VALUES
('mcq','Qui est le meilleur buteur de l''histoire de l''équipe de France ?','["Thierry Henry","Michel Platini","Olivier Giroud","Antoine Griezmann"]','Olivier Giroud','Giroud a dépassé Thierry Henry avec 57 buts en sélection.',1,(SELECT id FROM categories WHERE slug='equipe-de-france'),'{"records"}',''),
('mcq','En quelle année la France a-t-elle remporté son premier Euro ?','["1984","1998","2000","2016"]','1984','La France a remporté l''Euro 1984 à domicile avec Platini.',2,(SELECT id FROM categories WHERE slug='equipe-de-france'),'{"histoire"}','Euro'),
('tf','Didier Deschamps a été capitaine ET sélectionneur champion du monde.','["Vrai","Faux"]','Vrai','Deschamps a été capitaine en 1998 et sélectionneur en 2018.',1,(SELECT id FROM categories WHERE slug='equipe-de-france'),'{"légendes"}',''),
('mcq','Combien de buts Zinedine Zidane a-t-il marqués en équipe de France ?','["21","25","31","35"]','31','Zidane a inscrit 31 buts en 108 sélections avec les Bleus.',3,(SELECT id FROM categories WHERE slug='equipe-de-france'),'{"joueurs"}',''),
('mcq','Quel joueur a été élu meilleur jeune de la Coupe du Monde 2018 ?','["Paul Pogba","Antoine Griezmann","Kylian Mbappé","Raphaël Varane"]','Kylian Mbappé','Mbappé avait 19 ans lors du Mondial 2018, marquant 4 buts.',1,(SELECT id FROM categories WHERE slug='equipe-de-france'),'{"joueurs"}','Coupe du Monde'),
('whoami','J''ai inscrit un doublé en finale de l''Euro 2000. Je joue au milieu.','["Zinedine Zidane","Patrick Vieira","David Trezeguet","Sylvain Wiltord"]','David Trezeguet','Trezeguet a marqué le but en or en finale de l''Euro 2000.',4,(SELECT id FROM categories WHERE slug='equipe-de-france'),'{"légendes"}','Euro'),
('mcq','Contre quelle équipe la France a-t-elle perdu la finale de l''Euro 2016 ?','["Allemagne","Espagne","Portugal","Italie"]','Portugal','Le Portugal a battu la France 1-0 en prolongation au Stade de France.',1,(SELECT id FROM categories WHERE slug='equipe-de-france'),'{"histoire"}','Euro'),
('tf','N''Golo Kanté a remporté la Coupe du Monde ET la Champions League.','["Vrai","Faux"]','Vrai','Kanté a gagné le Mondial 2018 et la C1 2021 avec Chelsea.',2,(SELECT id FROM categories WHERE slug='equipe-de-france'),'{"joueurs"}','');

-- ═══ LIGA (extra) ═══
INSERT INTO questions (type, question, choices, answer, explanation, difficulty, category_id, tags, competition) VALUES
('mcq','Quel joueur a marqué le plus de buts en Liga ?','["Cristiano Ronaldo","Raúl","Telmo Zarra","Lionel Messi"]','Lionel Messi','Messi a inscrit 474 buts en Liga, un record absolu.',1,(SELECT id FROM categories WHERE slug='liga'),'{"records"}','Liga'),
('mcq','Combien de Liga le Real Madrid a-t-il remportées ?','["30","33","36","38"]','36','Le Real Madrid a remporté 36 titres de Liga (record).',3,(SELECT id FROM categories WHERE slug='liga'),'{"records"}','Liga'),
('tf','L''Atletico Madrid a remporté la Liga en 2021.','["Vrai","Faux"]','Vrai','L''Atletico de Simeone a remporté la Liga 2020-2021.',2,(SELECT id FROM categories WHERE slug='liga'),'{"histoire"}','Liga'),
('mcq','Quel Clasico détient le record de spectateurs ?','["Camp Nou 1982","Bernabéu 2004","Camp Nou 2017","Bernabéu 2022"]','Camp Nou 1982','Le Camp Nou a accueilli 120 000 spectateurs pour un Clasico en 1982.',5,(SELECT id FROM categories WHERE slug='liga'),'{"histoire"}','Liga'),
('mcq','Qui a remporté le trophée Pichichi (meilleur buteur) le plus souvent ?','["Cristiano Ronaldo","Lionel Messi","Hugo Sánchez","Telmo Zarra"]','Lionel Messi','Messi a remporté 8 trophées Pichichi.',2,(SELECT id FROM categories WHERE slug='liga'),'{"récompenses"}','Liga'),
('whoami','J''ai été le plus jeune buteur du Barça en Liga. Je suis espagnol et j''ai brillé à l''Euro 2024.','["Pedri","Gavi","Ansu Fati","Lamine Yamal"]','Lamine Yamal','Yamal est devenu le plus jeune buteur du Barça en Liga à 16 ans.',2,(SELECT id FROM categories WHERE slug='liga'),'{"joueurs"}','Liga'),
('mcq','Quel club espagnol a remporté l''Europa League 7 fois ?','["Atletico Madrid","FC Barcelone","Séville FC","Valencia CF"]','Séville FC','Séville est le club le plus titré en Europa League avec 7 trophées.',3,(SELECT id FROM categories WHERE slug='liga'),'{"coupes"}','Europa League'),
('tf','La Liga a été fondée avant la Premier League.','["Vrai","Faux"]','Vrai','La Liga a débuté en 1929, la Premier League en 1992.',1,(SELECT id FROM categories WHERE slug='liga'),'{"histoire"}','Liga');
